#!/bin/bash

#Script to set up custom thin client

# Run this script when setting up a new OS to be used as the thin client 

#Download git
#sudo apt install git

# Create user "kiosk" with password "kiosk"
sudo adduser kiosk
sermod -aG sudo kiosk
# Set up Auto Login

# Make kiosk script run on startup

# Get required software
sudo apt-get update -y

# Install YAD
sudo apt-get install -y yad

# Install X2GO
sudo apt-get install x2goclient

# Install Remmina
sudo apt-get install remmina -y

# Install Wireguard
sudo apt-get install wireguard -y

# Install konsole
sudo apt-get install konsole -y

# Install xpra
sudo apt-get install xpra -y

# Install OpenVPN
sudo apt-get install openvpn -y
